### ISSUE TITLE
Add Contributors details at the end of the readme file

### ISSUE THREAD

**Issue by akshatvirmani** [hackmamba-io/Technical-Writing-Course-with-Curriculum#7]
![image](https://github.com/user-attachments/assets/f9fd926b-2f75-47b3-af60-ad5a731b222e)
You might have seen the contributor's table in various repositories. Please add the table to this repository as well.

**Resources to do that:**
https://contrib.rocks/

**Comment by sammy-code98** [comment]
Hey @akshatvirmani  , can i work on this issue?

**Comment by akshatvirmani** [comment]
Hello @sammy-code98 
Thank you for showing your interest in the issue.
You can start working on this. I am assigning this to you!

**Comment by sammy-code98** [comment]
> Hello @sammy-code98 Thank you for showing your interest in the issue. You can start working on this. I am assigning this to you!

yeah sure. jumping right into it
